version: "2.3"
services:
  bnv_dashboard:
    image: dashboard:latest
    command: streamlit run dashboard/dashboard.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
        - ./:/usr/src/app
    ports:
        - 8501:8501
    networks:
      - bn_network
    # stdin_open: true
    # tty: true

  bnv_db:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./database/db:/data/db
    networks:
      - bn_network

  bnv_mongo_express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: bnv_db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - bnv_db
    logging:
      driver: none
    networks:
      - bn_network

  bnv_rabbitmq:
    restart: always
    image: rabbitmq:management
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bn_network

  bnv_worker:
    image: dashboard:latest
    working_dir: /usr/src/app/dashboard
    command: celery -A worker worker -l info
    volumes:
      - ./:/usr/src/app
    depends_on:
      - bnv_db
      - bnv_rabbitmq
    networks:
      - bn_network

  bnv_html_guidelines:
    image: dashboard:latest
    working_dir: /usr/src/app/dashboard
    command: python3 -m http.server 3000 --directory guidelines/
    volumes:
      - ./:/usr/src/app
    depends_on:
      - bnv_dashboard
    ports:
      - 3000:3000

networks:
  bn_network:
    driver: bridge
